# Generated by Django 4.0 on 2021-12-15 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=400, null=True)),
                ('blog_image', models.ImageField(upload_to='blog/')),
                ('blog_content', models.TextField(null=True)),
                ('up_to_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog', to='auth.user')),
            ],
        ),
    ]
