# Generated by Django 4.0 on 2021-12-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_blog_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_person',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
